{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  labels:
    {{- include "ms-app.labels" . | nindent 4 }}
data:
 {{ if .Values.secret.password }}
 MYSQLPASS: {{ .Values.secret.password | b64enc | quote  }} 
 {{- end }}
 {{- end }}
