apiVersion: v1
kind: Service
metadata:
  name: {{ include "ms-app.fullname" . }}-service-stage
  labels:
    {{- include "ms-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
{{- if .Values.extraPorts }}
{{ toYaml .Values.extraPorts | trim | indent 4 }}
{{- end }}
  selector:
    {{- include "ms-app.selectorLabels" . | nindent 4 }}
    {{- if eq .Values.productionSlot "blue" }}
    slot: green
    {{- else }}
    slot: blue
    {{- end }}
